Repository InsaLan/backend-insalan.fr, pull requests merged in 2023-12, with the labels that each got.

#102 Add custom ordering and filter to user Admin panel
  insalan/user/admin.py
Labels: enhancement

#107 Fix missing timeout
  insalan/payment/tokens.py
  insalan/payment/views.py
Labels: enhancement, priority:medium

#108 Fix dockerfile version not static
  Dockerfile
  Dockerfile.dev
Labels: bug, priority:high

#111 Harden payment notification reception path
  insalan/payment/views.py
Labels: enhancement, priority:medium

#115 Fix 500 when searching in admin panel
  insalan/payment/admin.py
  insalan/tickets/admin.py
  insalan/tournament/admin.py
Labels: bug

#117 Change settings to overwrite SESSION_COOKIE_AGE
  insalan/settings.py
Labels: bug, enhancement
