Repository InsaLan/backend-insalan.fr, pull requests merged in 2024-08, with the labels that each got.

#158 Fix 500 error when new team name is already used
  insalan/tournament/views/team.py
Labels: bug

#167 Fix Name validator
  insalan/tournament/models/validators.py
Labels: bug, priority:high

#168 Fix swiss match having wrong field name in tournament API
  insalan/tournament/views/tournament.py
Labels: bug, priority:high

#161 Add PUT, PATCH and DELETE methods for the pizzas.
  insalan/pizza/admin.py
  insalan/pizza/apps.py
  insalan/pizza/models.py
  insalan/pizza/serializers.py
  insalan/pizza/tests.py
  insalan/pizza/urls.py
  insalan/pizza/views.py
Labels: enhancement
